In [1]:
!export PIP_BREAK_SYSTEM_PACKAGES=1

In [5]:
!pip install pandas matplotlib seaborn duckdb numpy --break-system-packages

Collecting pandas
  Downloading pandas-2.3.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting duckdb
  Downloading duckdb-1.3.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Collecting numpy
  Downloading numpy-2.3.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.13/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.59.1-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (108 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.13/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 1.2 MB/s  0:00:10m0:00:0100:01
Downloading matplotlib-3.10.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 1.2 MB/s  0:00:07m0:00:0100:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading duckdb-1.3.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 1.2 MB/s  0:00:18m0:00:0100:01
Downloading numpy-2.3.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 1.2 MB/s  0:00:14m0:00:0100:01
Downloading contourpy-1.3.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.59.1-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 1.1 MB/s  0:00:04 eta 0:00:01
Downloading kiwisolver-1.4.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.1 MB/s  0:00:01 eta 0:00:01
Downloading pillow-11.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 1.2 MB/s  0:00:05m0:00:0100:01
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, duckdb, cycler, pandas, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [seaborn]1/12 [seaborn]ib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 duckdb-1.3.2 fonttools-4.59.1 kiwisolver-1.4.9 matplotlib-3.10.5 numpy-2.3.2 pandas-2.3.1 pillow-11.3.0 pyparsing-3.2.3 seaborn-0.13.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [9]:
!pip install openpyxl --break-system-packages

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [10]:
import os
import pandas as pd
import duckdb

In [12]:
file = os.path.join(".", "Estrutura.xlsx")
csv_file = os.path.join(".", "test.csv")

In [11]:
df = pd.read_excel(file)

In [13]:
df.to_csv(csv_file)

In [14]:
db = duckdb.read_csv(csv_file)

In [28]:
duckdb.sql("SELECT * FROM db WHERE altura >= 1.6 AND peso > 45;")

┌─────────┬───────┬──────────┬───────────┬────────┬────────┬────────┬─────────┬─────────┬───────────┐
│ column0 │  id   │   nome   │ sobrenome │  peso  │ altura │ idade  │ salario │  renda  │ prestacao │
│  int64  │ int64 │ varchar  │  varchar  │ double │ double │ double │ double  │ double  │  double   │
├─────────┼───────┼──────────┼───────────┼────────┼────────┼────────┼─────────┼─────────┼───────────┤
│       0 │     1 │ Edmar    │  caldas   │   88.8 │    1.7 │   40.9 │ 3001.99 │ 3001.99 │    550.99 │
│       1 │     2 │ Pedro    │ CALDAS    │   45.8 │   1.69 │   39.2 │  3110.1 │ 3110.11 │    601.99 │
│       3 │     4 │ cicero   │ alexandre │   72.1 │   1.67 │   37.6 │ 4110.99 │ 4110.99 │    450.99 │
│       4 │     5 │ joao     │ souza     │   75.9 │   1.66 │   36.1 │ 3801.54 │ 3801.54 │    380.21 │
│       5 │     6 │ MARIA    │ ferreira  │   45.8 │   3.05 │   35.4 │ 2987.01 │ 2987.01 │  10000.21 │
│       6 │     7 │ VINICIUS │ silva     │   50.9 │    2.1 │   34.9 │ 1550.99 │  2550.0 │   2509.65 │
└─────────┴───────┴──────────┴───────────┴────────┴────────┴────────┴─────────┴─────────┴───────────┘

In [21]:
df.head(7)

   id      nome  sobrenome  peso  altura  idade  salario    renda  prestacao
0   1     Edmar    caldas   88.8    1.70   40.9  3001.99  3001.99     550.99
1   2     Pedro    CALDAS   45.8    1.69   39.2  3110.10  3110.11     601.99
2   3   Matheus     CALDAS  33.7    1.68   38.7  2800.01  2800.01     700.56
3   4    cicero  alexandre  72.1    1.67   37.6  4110.99  4110.99     450.99
4   5      joao      souza  75.9    1.66   36.1  3801.54  3801.54     380.21
5   6     MARIA   ferreira  45.8    3.05   35.4  2987.01  2987.01   10000.21
6   7  VINICIUS      silva  50.9    2.10   34.9  1550.99  2550.00    2509.65

In [29]:
df.dtypes

id             int64
nome          object
sobrenome     object
peso         float64
altura       float64
idade        float64
salario      float64
renda        float64
prestacao    float64
dtype: object

In [30]:
df["idade"] = df["idade"].astype(int)

In [31]:
df

   id      nome  sobrenome  peso  altura  idade  salario    renda  prestacao
0   1     Edmar    caldas   88.8    1.70     40  3001.99  3001.99     550.99
1   2     Pedro    CALDAS   45.8    1.69     39  3110.10  3110.11     601.99
2   3   Matheus     CALDAS  33.7    1.68     38  2800.01  2800.01     700.56
3   4    cicero  alexandre  72.1    1.67     37  4110.99  4110.99     450.99
4   5      joao      souza  75.9    1.66     36  3801.54  3801.54     380.21
5   6     MARIA   ferreira  45.8    3.05     35  2987.01  2987.01   10000.21
6   7  VINICIUS      silva  50.9    2.10     34  1550.99  2550.00    2509.65

In [33]:
df[:]

   id      nome  sobrenome  peso  altura  idade  salario    renda  prestacao
0   1     Edmar    caldas   88.8    1.70     40  3001.99  3001.99     550.99
1   2     Pedro    CALDAS   45.8    1.69     39  3110.10  3110.11     601.99
2   3   Matheus     CALDAS  33.7    1.68     38  2800.01  2800.01     700.56
3   4    cicero  alexandre  72.1    1.67     37  4110.99  4110.99     450.99
4   5      joao      souza  75.9    1.66     36  3801.54  3801.54     380.21
5   6     MARIA   ferreira  45.8    3.05     35  2987.01  2987.01   10000.21
6   7  VINICIUS      silva  50.9    2.10     34  1550.99  2550.00    2509.65

In [34]:
df["comp_renda"] = df["prestacao"]/df["salario"]

In [35]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,0.183542
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,0.193560
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,0.250199
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,0.109704
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,0.100015
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,3.347900
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,1.618096

In [37]:
df["comp_renda"] = (df["prestacao"]/df["salario"]*100).round(2)

In [38]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81

In [39]:
df["prestacao_maior"] = df["salario"] >= df["prestacao"]

In [40]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False

In [42]:
df["salario_igual_renda"] = df["salario"] == df["renda"]

In [43]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False

In [53]:
df["IMC"] = (df["peso"]/(df["altura"]**2)).round(2)

In [55]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54

In [56]:
df["aumento_salario"] = (df["salario"]*1.1)

In [57]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089

In [64]:
df["nome_upper"] = df["nome"].str.upper()

In [65]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS

In [66]:
df["sobrenome_upper"] = df["sobrenome"].str.upper()

In [67]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA

In [72]:
df["nome_completo"] = df["nome_upper"] + " " + df["sobrenome_upper"]

In [73]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS,EDMAR CALDAS
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS,PEDRO CALDAS
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS,MATHEUS CALDAS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE,CICERO ALEXANDRE
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA,JOAO SOUZA
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA,MARIA FERREIRA
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA,VINICIUS SILVA

In [74]:
df["nome_completo_len"] = df["nome_completo"].str.len()

In [75]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS,EDMAR CALDAS,14
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS,PEDRO CALDAS,13
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS,MATHEUS CALDAS,15
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE,CICERO ALEXANDRE,16
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA,JOAO SOUZA,10
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA,MARIA FERREIRA,14
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA,VINICIUS SILVA,14

In [76]:
df["nome_completo"] = df["nome_completo"].str.capitalize()

In [77]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS,Edmar caldas,14
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS,Pedro caldas,13
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS,Matheus caldas,15
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE,Cicero alexandre,16
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA,Joao souza,10
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA,Maria ferreira,14
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA,Vinicius silva,14

In [81]:
df["sobrenome_len"] = df["sobrenome"].str.len()

In [82]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len,sobrenome_len
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS,Edmar caldas,14,8
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS,Pedro caldas,13,7
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS,Matheus caldas,15,7
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE,Cicero alexandre,16,9
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA,Joao souza,10,5
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA,Maria ferreira,14,8
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA,Vinicius silva,14,5

In [84]:
df["rstrip_sobrenome"] = df.sobrenome.str.rstrip()

In [85]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,prestacao_maior,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len,sobrenome_len,rstrip_sobrenome
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,True,True,30.73,3302.189,EDMAR,CALDAS,Edmar caldas,14,8,caldas
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,True,False,16.04,3421.110,PEDRO,CALDAS,Pedro caldas,13,7,CALDAS
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,True,True,11.94,3080.011,MATHEUS,CALDAS,Matheus caldas,15,7,CALDAS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,True,True,25.85,4522.089,CICERO,ALEXANDRE,Cicero alexandre,16,9,alexandre
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,True,True,27.54,4181.694,JOAO,SOUZA,Joao souza,10,5,souza
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,False,True,4.92,3285.711,MARIA,FERREIRA,Maria ferreira,14,8,ferreira
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,False,False,11.54,1706.089,VINICIUS,SILVA,Vinicius silva,14,5,silva

In [87]:
df["lstrip_sobrenome"] = df.sobrenome.str.lstrip()

In [88]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,...,salario_igual_renda,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len,sobrenome_len,rstrip_sobrenome,lstrip_sobrenome
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,...,True,30.73,3302.189,EDMAR,CALDAS,Edmar caldas,14,8,caldas,caldas
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,...,False,16.04,3421.110,PEDRO,CALDAS,Pedro caldas,13,7,CALDAS,CALDAS
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,...,True,11.94,3080.011,MATHEUS,CALDAS,Matheus caldas,15,7,CALDAS,CALDAS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,...,True,25.85,4522.089,CICERO,ALEXANDRE,Cicero alexandre,16,9,alexandre,alexandre
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,...,True,27.54,4181.694,JOAO,SOUZA,Joao souza,10,5,souza,souza
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,...,True,4.92,3285.711,MARIA,FERREIRA,Maria ferreira,14,8,ferreira,ferreira
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,...,False,11.54,1706.089,VINICIUS,SILVA,Vinicius silva,14,5,silva,silva

In [90]:
df["strip_sobrenome"] = df.sobrenome.str.strip()

In [91]:
df

,id,nome,sobrenome,peso,altura,idade,salario,renda,prestacao,comp_renda,...,IMC,aumento_salario,nome_upper,sobrenome_upper,nome_completo,nome_completo_len,sobrenome_len,rstrip_sobrenome,lstrip_sobrenome,strip_sobrenome
0,1,Edmar,caldas,88.8,1.70,40,3001.99,3001.99,550.99,18.35,...,30.73,3302.189,EDMAR,CALDAS,Edmar caldas,14,8,caldas,caldas,caldas
1,2,Pedro,CALDAS,45.8,1.69,39,3110.10,3110.11,601.99,19.36,...,16.04,3421.110,PEDRO,CALDAS,Pedro caldas,13,7,CALDAS,CALDAS,CALDAS
2,3,Matheus,CALDAS,33.7,1.68,38,2800.01,2800.01,700.56,25.02,...,11.94,3080.011,MATHEUS,CALDAS,Matheus caldas,15,7,CALDAS,CALDAS,CALDAS
3,4,cicero,alexandre,72.1,1.67,37,4110.99,4110.99,450.99,10.97,...,25.85,4522.089,CICERO,ALEXANDRE,Cicero alexandre,16,9,alexandre,alexandre,alexandre
4,5,joao,souza,75.9,1.66,36,3801.54,3801.54,380.21,10.00,...,27.54,4181.694,JOAO,SOUZA,Joao souza,10,5,souza,souza,souza
5,6,MARIA,ferreira,45.8,3.05,35,2987.01,2987.01,10000.21,334.79,...,4.92,3285.711,MARIA,FERREIRA,Maria ferreira,14,8,ferreira,ferreira,ferreira
6,7,VINICIUS,silva,50.9,2.10,34,1550.99,2550.00,2509.65,161.81,...,11.54,1706.089,VINICIUS,SILVA,Vinicius silva,14,5,silva,silva,silva

In [92]:
df.to_excel("novo.xlsx")

In [93]:
df.to_csv(csv_file)

In [41]:
duckdb.sql("UPDATE db SET nome = lower(nome);")

BinderException: Binder Error: Can only update base table!

In [44]:
con = duckdb.connect(database=':memory:')

In [45]:
con.execute("CREATE TABLE data_table AS SELECT * FROM read_csv_auto('test.csv')")

In [46]:
con.sql("select * from data_table")

┌─────────┬───────┬──────────┬───────────┬────────┬────────┬────────┬─────────┬─────────┬───────────┐
│ column0 │  id   │   nome   │ sobrenome │  peso  │ altura │ idade  │ salario │  renda  │ prestacao │
│  int64  │ int64 │ varchar  │  varchar  │ double │ double │ double │ double  │ double  │  double   │
├─────────┼───────┼──────────┼───────────┼────────┼────────┼────────┼─────────┼─────────┼───────────┤
│       0 │     1 │ Edmar    │  caldas   │   88.8 │    1.7 │   40.9 │ 3001.99 │ 3001.99 │    550.99 │
│       1 │     2 │ Pedro    │ CALDAS    │   45.8 │   1.69 │   39.2 │  3110.1 │ 3110.11 │    601.99 │
│       2 │     3 │ Matheus  │  CALDAS   │   33.7 │   1.68 │   38.7 │ 2800.01 │ 2800.01 │    700.56 │
│       3 │     4 │ cicero   │ alexandre │   72.1 │   1.67 │   37.6 │ 4110.99 │ 4110.99 │    450.99 │
│       4 │     5 │ joao     │ souza     │   75.9 │   1.66 │   36.1 │ 3801.54 │ 3801.54 │    380.21 │
│       5 │     6 │ MARIA    │ ferreira  │   45.8 │   3.05 │   35.4 │ 2987.01 │ 2987.01 │  10000.21 │
│       6 │     7 │ VINICIUS │ silva     │   50.9 │    2.1 │   34.9 │ 1550.99 │  2550.0 │   2509.65 │
└─────────┴───────┴──────────┴───────────┴────────┴────────┴────────┴─────────┴─────────┴───────────┘

In [51]:
con.sql("UPDATE data_table SET nome=lower(nome), sobrenome=lower(sobrenome), idade=trunc(idade);")

In [52]:
con.sql("select * from data_table")

┌─────────┬───────┬──────────┬───────────┬────────┬────────┬────────┬─────────┬─────────┬───────────┐
│ column0 │  id   │   nome   │ sobrenome │  peso  │ altura │ idade  │ salario │  renda  │ prestacao │
│  int64  │ int64 │ varchar  │  varchar  │ double │ double │ double │ double  │ double  │  double   │
├─────────┼───────┼──────────┼───────────┼────────┼────────┼────────┼─────────┼─────────┼───────────┤
│       0 │     1 │ edmar    │  caldas   │   88.8 │    1.7 │   40.0 │ 3001.99 │ 3001.99 │    550.99 │
│       1 │     2 │ pedro    │ caldas    │   45.8 │   1.69 │   39.0 │  3110.1 │ 3110.11 │    601.99 │
│       2 │     3 │ matheus  │  caldas   │   33.7 │   1.68 │   38.0 │ 2800.01 │ 2800.01 │    700.56 │
│       3 │     4 │ cicero   │ alexandre │   72.1 │   1.67 │   37.0 │ 4110.99 │ 4110.99 │    450.99 │
│       4 │     5 │ joao     │ souza     │   75.9 │   1.66 │   36.0 │ 3801.54 │ 3801.54 │    380.21 │
│       5 │     6 │ maria    │ ferreira  │   45.8 │   3.05 │   35.0 │ 2987.01 │ 2987.01 │  10000.21 │
│       6 │     7 │ vinicius │ silva     │   50.9 │    2.1 │   34.0 │ 1550.99 │  2550.0 │   2509.65 │
└─────────┴───────┴──────────┴───────────┴────────┴────────┴────────┴─────────┴─────────┴───────────┘

In [61]:
con.sql("ALTER TABLE data_table ALTER COLUMN idade TYPE BIGINT")

In [63]:
con.sql("select * from data_table")

┌─────────┬───────┬──────────┬───────────┬────────┬────────┬───────┬─────────┬─────────┬───────────┐
│ column0 │  id   │   nome   │ sobrenome │  peso  │ altura │ idade │ salario │  renda  │ prestacao │
│  int64  │ int64 │ varchar  │  varchar  │ double │ double │ int64 │ double  │ double  │  double   │
├─────────┼───────┼──────────┼───────────┼────────┼────────┼───────┼─────────┼─────────┼───────────┤
│       0 │     1 │ edmar    │  caldas   │   88.8 │    1.7 │    40 │ 3001.99 │ 3001.99 │    550.99 │
│       1 │     2 │ pedro    │ caldas    │   45.8 │   1.69 │    39 │  3110.1 │ 3110.11 │    601.99 │
│       2 │     3 │ matheus  │  caldas   │   33.7 │   1.68 │    38 │ 2800.01 │ 2800.01 │    700.56 │
│       3 │     4 │ cicero   │ alexandre │   72.1 │   1.67 │    37 │ 4110.99 │ 4110.99 │    450.99 │
│       4 │     5 │ joao     │ souza     │   75.9 │   1.66 │    36 │ 3801.54 │ 3801.54 │    380.21 │
│       5 │     6 │ maria    │ ferreira  │   45.8 │   3.05 │    35 │ 2987.01 │ 2987.01 │  10000.21 │
│       6 │     7 │ vinicius │ silva     │   50.9 │    2.1 │    34 │ 1550.99 │  2550.0 │   2509.65 │
└─────────┴───────┴──────────┴───────────┴────────┴────────┴───────┴─────────┴─────────┴───────────┘

In [78]:
con.sql("ATTACH 'file.db';")

In [79]:
con.sql("COPY FROM DATABASE memory TO file")

In [80]:
con.sql("DETACH file;")

In [95]:
series = df.salario
series

0    3001.99
1    3110.10
2    2800.01
3    4110.99
4    3801.54
5    2987.01
6    1550.99
Name: salario, dtype: float64

In [96]:
series.min()

np.float64(1550.99)

In [97]:
series.max()

np.float64(4110.99)

In [98]:
series.sum()

np.float64(21362.63)

In [100]:
series.idxmin()

6

In [101]:
series.mean()

np.float64(3051.804285714286)

In [102]:
series.median()

np.float64(3001.99)

In [104]:
series.idxmax()

3

In [107]:
series.iloc[series.idxmax()]

np.float64(4110.99)

In [108]:
df.shape

(7, 22)

In [109]:
series.shape

(7,)

In [111]:
assert (series.sum()/series.count()) == series.mean(), "NN É ISSO"

In [112]:
series.std()

np.float64(817.506376526755)