In [7]:
!pip install pandas seaborn matplotlib openpyxl --break-system-packages

Requirement already satisfied: pandas in /usr/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: seaborn in /usr/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/lib/python3.13/site-packages (3.10.6)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/lib/python3.13/site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.13/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/lib/python3.13/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [5]:
data_file_path = "Arquivo Cadastral.xlsx"

In [3]:
import pandas as pd

In [10]:
cadastral = pd.read_excel(data_file_path,skiprows=1)
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0

In [11]:
cadastral.tail()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
4428,4305,1948-06-01,2,1,2,8527.50,1,3.0,813.0
4429,4336,1951-02-15,1,1,1,6331.46,2,3.0,772.0
4430,4371,1965-05-11,1,2,2,7657.87,2,3.0,106.0
4431,4402,1969-03-16,1,2,1,9134.69,2,3.0,884.0
4432,4414,1963-07-21,2,2,0,9192.60,3,3.0,417.0

In [12]:
cadastral.dtypes

id                          int64
datanasc           datetime64[ns]
sexo                        int64
estado_civil                int64
numeros_filhos              int64
renda_familiar            float64
pagamento_plano             int64
catemp                    float64
valor_prestacao           float64
dtype: object

In [14]:
cadastral.sort_values(by="id").head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1465,1,1968-11-05,2,1,0,7768.00,2,3.0,584.0
1464,1,1968-11-05,1,1,0,7768.00,2,3.0,584.0
195,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
196,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
2363,3,1966-02-21,1,1,1,3707.94,1,3.0,992.0

In [15]:
cadastral.shape

(4433, 9)

In [16]:
cadastral.sort_values(["sexo", "renda_familiar"],ascending=False).head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1084,1045,1937-11-25,2,1,1,9961.99,2,3.0,372.0
1408,3261,1953-06-09,2,1,1,9961.99,2,3.0,959.0
1608,255,1963-08-17,2,1,1,9961.99,2,3.0,76.0
215,842,1966-11-13,2,1,0,9956.31,2,3.0,951.0
412,3789,1966-10-14,2,1,0,9956.31,2,3.0,105.0

In [17]:
cadastral1 = cadastral.drop_duplicates()

In [18]:
cadastral1.sort_values(by="id").head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1464,1,1968-11-05,1,1,0,7768.00,2,3.0,584.0
1465,1,1968-11-05,2,1,0,7768.00,2,3.0,584.0
195,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
2363,3,1966-02-21,1,1,1,3707.94,1,3.0,992.0
2102,4,1966-08-03,2,2,2,8199.70,3,3.0,905.0

In [19]:
cadastral1.sort_values(["sexo", "renda_familiar"],ascending=False).head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1084,1045,1937-11-25,2,1,1,9961.99,2,3.0,372.0
1408,3261,1953-06-09,2,1,1,9961.99,2,3.0,959.0
1608,255,1963-08-17,2,1,1,9961.99,2,3.0,76.0
215,842,1966-11-13,2,1,0,9956.31,2,3.0,951.0
412,3789,1966-10-14,2,1,0,9956.31,2,3.0,105.0

In [20]:
cadastral1.shape

(4432, 9)

In [21]:
cadastral2 = cadastral1.drop_duplicates(subset="id", keep="first")
cadastral2.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0

In [22]:
cadastral2.shape

(4431, 9)

In [23]:
cadastral2.sort_values(by="id").head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1464,1,1968-11-05,1,1,0,7768.00,2,3.0,584.0
195,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
2363,3,1966-02-21,1,1,1,3707.94,1,3.0,992.0
2102,4,1966-08-03,2,2,2,8199.70,3,3.0,905.0
321,5,1964-01-22,1,2,0,1682.96,1,3.0,575.0

In [24]:
cadastral3 = cadastral1.drop_duplicates(subset="id", keep="last")
cadastral3.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0

In [25]:
cadastral3.sort_values(by="id").head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
1465,1,1968-11-05,2,1,0,7768.00,2,3.0,584.0
195,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
2363,3,1966-02-21,1,1,1,3707.94,1,3.0,992.0
2102,4,1966-08-03,2,2,2,8199.70,3,3.0,905.0
321,5,1964-01-22,1,2,0,1682.96,1,3.0,575.0

In [26]:
cadastral3.shape

(4431, 9)

In [31]:
cadastral4 = cadastral1.drop_duplicates(subset="id", keep=False)
cadastral4.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0

In [32]:
cadastral4.shape

(4430, 9)

In [33]:
cadastral4.sort_values(by="id").head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao
195,2,1937-11-25,2,2,1,3711.15,1,NaN,68.0
2363,3,1966-02-21,1,1,1,3707.94,1,3.0,992.0
2102,4,1966-08-03,2,2,2,8199.70,3,3.0,905.0
321,5,1964-01-22,1,2,0,1682.96,1,3.0,575.0
1337,6,1964-06-01,2,1,1,5727.27,2,3.0,501.0

In [30]:
from datetime import date
cadastral["data_atual"] = date.today()

In [34]:
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02

In [35]:
cadastral.dtypes

id                          int64
datanasc           datetime64[ns]
sexo                        int64
estado_civil                int64
numeros_filhos              int64
renda_familiar            float64
pagamento_plano             int64
catemp                    float64
valor_prestacao           float64
data_atual                 object
dtype: object

In [36]:
cadastral["data_atual"] = cadastral["data_atual"].astype('datetime64[ns]')
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02

In [37]:
cadastral.dtypes

id                          int64
datanasc           datetime64[ns]
sexo                        int64
estado_civil                int64
numeros_filhos              int64
renda_familiar            float64
pagamento_plano             int64
catemp                    float64
valor_prestacao           float64
data_atual         datetime64[ns]
dtype: object

In [38]:
cadastral["idade"] = (cadastral["data_atual"] - cadastral["datanasc"]) / 365.25
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual,idade
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02,61 days 17:00:07.392197125
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02,80 days 04:35:58.521560575
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02,60 days 09:27:43.244353183
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02,63 days 14:59:52.607802875
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02,64 days 02:41:38.562628337

In [39]:
cadastral.dtypes

id                           int64
datanasc            datetime64[ns]
sexo                         int64
estado_civil                 int64
numeros_filhos               int64
renda_familiar             float64
pagamento_plano              int64
catemp                     float64
valor_prestacao            float64
data_atual          datetime64[ns]
idade              timedelta64[ns]
dtype: object

In [40]:
import numpy as np
cadastral["idade"] = cadastral["idade"].dt.days.astype(int)
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual,idade
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02,61
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02,80
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02,60
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02,63
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02,64

In [41]:
cadastral.dtypes

id                          int64
datanasc           datetime64[ns]
sexo                        int64
estado_civil                int64
numeros_filhos              int64
renda_familiar            float64
pagamento_plano             int64
catemp                    float64
valor_prestacao           float64
data_atual         datetime64[ns]
idade                       int64
dtype: object

In [42]:
cadastral.describe().idade

count    4433.000000
mean       68.424092
min        54.000000
25%        60.000000
50%        63.000000
75%        77.000000
max        96.000000
std        11.898475
Name: idade, dtype: float64

In [43]:
cadastral["sexo_organizado"] = pd.cut(cadastral["sexo"], bins=[0,1,2], labels=["Feminino", "Masculino"])
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual,idade,sexo_organizado
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02,61,Masculino
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02,80,Feminino
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02,60,Feminino
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02,63,Feminino
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02,64,Feminino

In [44]:
cadastral.sexo_organizado.value_counts()

sexo_organizado
Feminino     2244
Masculino    2189
Name: count, dtype: int64

In [46]:
cadastral["Estado_Civil"] =  pd.cut(cadastral["estado_civil"], bins=[0,1,2], labels=["casado", "solteiro"])
cadastral["plano_pagamento"] =  pd.cut(cadastral["pagamento_plano"], bins=[0,1,2,3], labels=["debito conta", "boleto", "cartao credito"])
cadastral["cat_emprego"] =  pd.cut(cadastral["catemp"], bins=[0,1,2,3], labels=["A", "B", "C"])
cadastral["faixa_etaria"] =  pd.cut(cadastral["idade"], bins=[min(cadastral.idade)-1,58,62,76,max(cadastral.idade)+1], labels=["A", "B", "C", "D"])

In [47]:
print(cadastral["Estado_Civil"].value_counts())
print(cadastral["plano_pagamento"].value_counts())
print(cadastral["cat_emprego"].value_counts())
print(cadastral["faixa_etaria"].value_counts())

Estado_Civil
casado      2629
solteiro    1804
Name: count, dtype: int64
plano_pagamento
boleto            2563
cartao credito     978
debito conta       892
Name: count, dtype: int64
cat_emprego
C    3371
A     778
B     248
Name: count, dtype: int64
faixa_etaria
C    1231
B    1219
D    1151
A     832
Name: count, dtype: int64

In [48]:
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual,idade,sexo_organizado,Estado_Civil,plano_pagamento,cat_emprego,faixa_etaria
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02,61,Masculino,solteiro,boleto,A,B
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02,80,Feminino,casado,boleto,A,D
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02,60,Feminino,casado,cartao credito,A,B
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02,63,Feminino,solteiro,cartao credito,NaN,C
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02,64,Feminino,casado,boleto,A,C

In [49]:
cadastral["faixa_etaria"] = pd.qcut(cadastral["idade"],q=3)
cadastral.head()

,id,datanasc,sexo,estado_civil,numeros_filhos,renda_familiar,pagamento_plano,catemp,valor_prestacao,data_atual,idade,sexo_organizado,Estado_Civil,plano_pagamento,cat_emprego,faixa_etaria
0,20,1964-01-17,2,2,1,5223.150,2,1.0,283.0,2025-10-02,61,Masculino,solteiro,boleto,A,"(53.999, 61.0]"
1,168,1945-07-24,1,1,1,7308.970,2,1.0,446.0,2025-10-02,80,Feminino,casado,boleto,A,"(71.0, 96.0]"
2,199,1965-05-11,1,1,2,4887.470,3,1.0,293.0,2025-10-02,60,Feminino,casado,cartao credito,A,"(53.999, 61.0]"
3,409,1962-02-16,1,2,0,2389.220,3,NaN,737.0,2025-10-02,63,Feminino,solteiro,cartao credito,NaN,"(61.0, 71.0]"
4,440,1961-08-22,1,1,1,297.691,2,1.0,457.0,2025-10-02,64,Feminino,casado,boleto,A,"(61.0, 71.0]"

In [50]:
cadastral["faixa_etaria"].value_counts()

faixa_etaria
(53.999, 61.0]    1738
(71.0, 96.0]      1438
(61.0, 71.0]      1257
Name: count, dtype: int64

In [51]:
pd.crosstab(cadastral.Estado_Civil, cadastral.estado_civil)

estado_civil     1     2
Estado_Civil
casado        2629     0
solteiro         0  1804

In [52]:
pd.crosstab(cadastral.cat_emprego, cadastral.catemp)

catemp       1.0  2.0   3.0
cat_emprego
A            778    0     0
B              0  248     0
C              0    0  3371